#!/usr/bin/env ruby

require 'telegram/bot'

# token:
# 1. Write your TOKEN value into "token" variable or
# 2. Create a local file "hiden.token" with your TOKEN value inside
token = `cat hide.token`.strip
bot_username = '@bot_LawD17'

puts "[INFO] Running bot #{$0}..."

Telegram::Bot::Client.run(token) do |bot|
  bot.listen do |message|
    puts "¿Qué puede hacer este bot?
      bot_LawD17 es un bot que que se encarga
      de dar iformacion de una maquina operativa.

      Para ver las opciones que puede realizar usa /help"
    if message.text == "/help"
      puts ""
    elsif message.text == "/hello"
      bot.api.send_message(chat_id: message.chat.id, text: "Hello")
    elsif message.text == "/byebye"
      bot.api.send_message(chat_id: message.chat.id, text: "Bye bye!")
    elsif message.text == "/ip"
      items = `ip a | grep 'inet ' | grep -v 'host lo'`.split
      bot.api.send_message(chat_id: message.chat.id, text: "La ip actual de la maquina es #{items[1]}")
    elsif message.text == "/hostname"
      hostname = `hostname -d`
      bot.api.send_message(chat_id: message.chat.id, text: hostname)
    elsif message.text == "/you"
      bot.api.send_message(chat_id: message.chat.id, text: "Soy un bot diseñado para dar informacion de la maquina #{`hostname -d`}.")
    end
  end
end
