#!/usr/bin/ruby
require_relative 'run'
require_relative 'status'
argument1 = ARGV[0]
argument2 = ARGV[1]
def help
  puts'
  Usage:
        systemctml [OPTIONS] [FILENAME]
Options:
        --help, mostrar esta ayuda.
        --version, mostrar información sobre el autor del script
                   y fecha de creacion.
        --status FILENAME, comprueba si puede instalar/desintalar.
        --run FILENAME, instala/desinstala el software indicado.
Description:

        Este script se encarga de instalar/desinstalar
        el software indicado en el fichero FILENAME.
        Ejemplo de FILENAME:
        tree:install
        nmap:install
        atomix:remove'
end

def version
  puts "
  softwarectl 1.0
  2019 Developed by Jonay Hernández Izquierdo.
  This is free software: you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.
  "
end

def option(file)
  if argument1 == "--help"
    help
  elsif argument1 == "--version"
    version
  elsif argument1 == "--status" and argument2.nil?
    status(file)
  elsif argument1 == "--run" and argument2.nil?
    run(file)
  else
    puts "softwarectl: opción inválida --'#{argument1}'".colorize(:red)
    puts "Pruebe 'softwarectl --help' para más información.".colorize(:red)
  end
end
