#!/usr/bin/ruby
require 'colorize'
def check_file
  ok = system("cat files/#{ARGV[1]} > /dev/null")
  if ok
    file = Hash.new
    open("files/#{ARGV[1]}", 'r') do |l|
      while line = l.gets
        line = line.split(":")
        file[line[0]] = line[1]
      end
    end
    return file
  else
    puts "El fichero o directorio no existe".colorize(:red)
  end
end
