#!/usr/bin/ruby
require 'colorize'
require_relative 'read_file'
def check_program(program)
    check = `whereis #{program} | grep bin | wc -l`.to_i
    bool = 0
    if check == 0
      bool = 0
      return bool
    elsif check == 1
      bool = 1
      return bool
    else
      puts "Error en los datos del fichero".colorize(:red)
      puts "install para instalar y remove para desinstalar".colorize(:red)
    end
end

def status(file)
  file.each do |key,value|
    bool = check_program(key)
    if bool
      puts "-- #{key} (I) installed".colorize(:light)
    else
      puts "-- #{key} (U) unistalled".colorize(:bold)
    end
  end
end
